baseurl = "https://spinkney.github.io"
title = "sp"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Sean Pinkney"
disqusShortname = "XXX"
googleAnalytics = "XXX"
publishDir = "../spinkney.github.io"

[Author]
    name = "Sean Pinkney"
    profile = "https://github.com/spinkney"
    
[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "too data"
    description = "too bayes"
    github = "https://github.com/spinkney"
    # gitlab = "https://gitlab.com/XXX"
    linkedin = "https://linkedin.com/in/sean-pinkney-0009b910/"
    # gplus = "https://google.com/+XXX"
    # twitter = "https://twitter.com/XXX"
    # stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "sean.pinkney@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
